branch-defaults:
  default:
    environment: parseserver
  master:
    environment: parseserver
global:
  application_name: ParseServer
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: null
